# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.13.0 on Sat May  4 04:03:10 2024
# Model: Annual Water Yield

import logging
import sys

import natcap.invest.annual_water_yield
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'biophysical_table_path': '/Users/shunkeikakimoto/Files/base_data/mesh/biophysical_table.csv',
    'demand_table_path': '',
    'depth_to_root_rest_layer_path': '/Users/shunkeikakimoto/Files/base_data/mesh/isric/depth_to_root_restricting_layer_slv.tif',
    'eto_path': '/Users/shunkeikakimoto/Files/base_data/mesh/cgiar_csi/pet_slv.tif',
    'lulc_path': '/Users/shunkeikakimoto/Files/base_data/seals_out_lulcssp1_rcp26/slv_lulc_esa_seals7_ssp1_rcp26_luh2-message_bau_2030_clipped.tif',
    'pawc_path': '/Users/shunkeikakimoto/Files/base_data/mesh/soil/pawc_slv.tif',
    'precipitation_path': '/Users/shunkeikakimoto/Files/base_data/mesh/worldclim/ppt_slv.tif',
    'results_suffix': '',
    'seasonality_constant': '20',
    'sub_watersheds_path': '',
    'valuation_table_path': '',
    'watersheds_path': '/Users/shunkeikakimoto/Files/base_data/mesh/hydrosheds/hydrobasin_slv_lev06.shx',
    'workspace_dir': '/Users/shunkeikakimoto/Files/apec_8601/apec_8601_2024/final_assignment/InVEST_out/ssp1_rcp26/AnnualWaterYield/y2030',
}

if __name__ == '__main__':
    natcap.invest.annual_water_yield.execute(args)
