# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.13.0 on Sun May  5 17:26:01 2024
# Model: Sediment Delivery Ratio

import logging
import sys

import natcap.invest.sdr.sdr
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'biophysical_table_path': '/Users/shunkeikakimoto/Files/base_data/mesh/biophysical_table.csv',
    'dem_path': '/Users/shunkeikakimoto/Files/base_data/mesh/DEM/slv_elev.tif',
    'drainage_path': '',
    'erodibility_path': '/Users/shunkeikakimoto/Files/base_data/mesh/soil_erodibility/slv_K_factor_soil_erodibility.tif',
    'erosivity_path': '/Users/shunkeikakimoto/Files/base_data/mesh/erosivity/slv_R_factor_rainfall_erosivity.tif',
    'ic_0_param': '0.5',
    'k_param': '2',
    'l_max': '122',
    'lulc_path': '/Users/shunkeikakimoto/Files/base_data/seals_out_lulc/slv_lulc_esa_seals7_ssp1_rcp26_luh2-message_bau_2030_clipped.tif',
    'results_suffix': '',
    'sdr_max': '0.8',
    'threshold_flow_accumulation': '1000',
    'watersheds_path': '/Users/shunkeikakimoto/Files/base_data/mesh/hydrosheds/hydrobasin_slv_lev06.shp',
    'workspace_dir': '/Users/shunkeikakimoto/Files/base_data/slv_InVEST_out/ssp1_rcp26/SedimentRetention/y2030',
}

if __name__ == '__main__':
    natcap.invest.sdr.sdr.execute(args)
